project:
  type: website
  output-dir: docs
 
website:
  navbar:
    background: "light"
    title: "Lena Vogl"
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "R & Excel"
        file: Excel.qmd
      - text: "Karten mit R leaflet"
        file: Leaflet.qmd
      - text: "Observable JS"
        file: Observable.qmd
      - text: "Impressum"
        file: Impressum.qmd
      - icon: github
        href: https://github.com/LenaVogl/
   
comments:
  giscus:
    repo: LenaVogl/lenavogl.github.io



format:
  html:
    page-layout: full
    theme: lux
    css: style.css

